services:
  - type: worker
    name: chatgpt-auto-bot
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python bot_main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_IDS
        sync: false
